import React, { useState } from "react";
import Handle from "rc-slider/lib/Handles/Handle";
import { headers } from "@/next.config";
import axios from "axios";

const OnlineSchoolForm = () => {
  const [focusedInput, setFocusedInput] = useState(null);
  const [formData, setFormData] = useState({
    name: "",
    phone: "",
    email: "",
    interested: "", // Fixed typo from 'intrested' to 'interested'
    message: "",
  });

  const handleChange = (e) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
  
    // Create FormData object for Contact Form 7
    const formDataObj = new FormData();
    formDataObj.append("your-name", formData.name); // Ensure 'your-name' matches the name attribute of the input in CF7
    formDataObj.append("tel-543", formData.phone); // Ensure the phone field matches the CF7 form input
    formDataObj.append("your-email", formData.email); // Ensure 'your-email' matches the name attribute of the input in CF7
    formDataObj.append("Interestedin", formData.interested); // Ensure this is the correct name attribute
    formDataObj.append("your-message", formData.message); // Ensure this is the correct name attribute
    formDataObj.append("_wpcf7", "16889"); // Replace with your actual Contact Form ID
    formDataObj.append("_wpcf7_version", "5.9.8"); // Replace with your CF7 version
    formDataObj.append("_wpcf7_locale", "en_US"); // Ensure this matches your locale
    formDataObj.append("_wpcf7_unit_tag", "wpcf7-f16889-p16890-o1"); // Correct unit tag for your form
    formDataObj.append("_wpcf7_container_post", "16890"); // Correct container post
    formDataObj.append("_wpcf7_posted_data_hash", ""); // Leave empty or use the hash generated by CF7
    formDataObj.append("_wpcf7cf_hidden_group_fields", "[]"); // Additional data, if any
    formDataObj.append("_wpcf7cf_hidden_groups", "[]"); // Additional data, if any
    formDataObj.append("_wpcf7cf_visible_groups", "[]"); // Additional data, if any
    formDataObj.append("_wpcf7cf_repeaters", "[]"); // Additional data, if any
    formDataObj.append("_wpcf7cf_steps", "{}"); // Additional data, if any
    
    // Add the quiz answer (if applicable)
    formDataObj.append("quiz", "four+5?=9"); // Replace with the actual correct answer to the quiz
  
    try {
      const response = await axios({
        method: "post",
        url: "https://irepute.in/wp-json/contact-form-7/v1/contact-forms/16889/feedback",
        data: formDataObj,
        headers: {
          "Content-Type": "multipart/form-data",
        },
      });
  
      if (response.data.status === "mail_sent") {
        // Success case
        console.log("Form submitted successfully");
        // Reset form
        setFormData({
          name: "",
          phone: "",
          email: "",
          interested: "",
          message: "",
        });
        // Success message handling
        alert("Thank you for your message!");
      } else {
        // Handle validation errors
        console.log("Validation errors:", response.data.invalid_fields);
        alert("Please check your form entries and try again.");
      }
    } catch (error) {
      console.error("Submission error:", error);
      alert("There was an error submitting the form. Please try again later.");
    }
  };
  

  return (
    <div className="rbt-contact-form contact-form-style-1">
      <h4 className="title" style={{ fontWeight: "500" }}>
        Let’s Get
        <br /> On A Discovery Call
      </h4>
      {/* <form id="contact-form" onSubmit={handleSubmit}>
        <div
          className={`form-group ${focusedInput === "name" ? "focused" : ""}`}
        >
          <input
            name="name"
            type="text"
            placeholder="Name"
            onFocus={() => setFocusedInput("name")}
            onBlur={() => setFocusedInput(null)}
            onChange={handleChange}
            value={formData.name}
          />
          <span className="focus-border"></span>
        </div>

        <div
          className={`form-group ${focusedInput === "phone" ? "focused" : ""}`}
        >
          <input
            name="phone"
            type="text"
            placeholder="Phone"
            onFocus={() => setFocusedInput("phone")}
            onBlur={() => setFocusedInput(null)}
            onChange={handleChange}
            value={formData.phone}
          />
          <span className="focus-border"></span>
        </div>

        <div
          className={`form-group ${focusedInput === "email" ? "focused" : ""}`}
        >
          <input
            name="email"
            placeholder="Email"
            type="email"
            onFocus={() => setFocusedInput("email")}
            onBlur={() => setFocusedInput(null)}
            onChange={handleChange}
            value={formData.email}
          />
          <span className="focus-border"></span>
        </div>

        <div
          className={`form-group ${
            focusedInput === "interested" ? "focused" : ""
          }`}
        >
          <select
            name="interested"
            onFocus={() => setFocusedInput("interested")}
            onBlur={() => setFocusedInput(null)}
            onChange={handleChange}
            value={formData.interested}
          >
            <option value="">Interested In</option>
            <option value="Branding">Branding</option>
            <option value="Logo Design">Logo Design</option>
            <option value="Brochure Design">Brochure Design</option>
            <option value="Website Design">Website Design</option>
            <option value="CMS Website Development">
              CMS Website Development
            </option>
            <option value="e-Commerce Website Development">
              e-Commerce Website Development
            </option>
            <option value="Mobile App Development">
              Mobile App Development
            </option>
            <option value="Search Engine Optimization">
              Search Engine Optimization
            </option>
            <option value="Social Media Marketing">
              Social Media Marketing
            </option>
            <option value="Pay-Per-Click">Pay-Per-Click</option>
            <option value="Amazon Listing Services">
              Amazon Listing Services
            </option>
            <option value="Corporate Video">Corporate Video</option>
          </select>
          <span className="focus-border"></span>
        </div>

        <div
          className={`form-group ${
            focusedInput === "message" ? "focused" : ""
          }`}
        >
          <textarea
            name="message"
            onFocus={() => setFocusedInput("message")}
            onBlur={() => setFocusedInput(null)}
            placeholder="Message"
            onChange={handleChange}
            value={formData.message}
          ></textarea>
          <span className="focus-border"></span>
        </div>

        <div className="form-submit-group">
          <button
            type="submit"
            className="rbt-btn btn-md btn-gradient hover-icon-reverse radius-round w-100"
          >
            <span className="icon-reverse-wrapper">
              <span className="btn-text">Submit</span>
              <span className="btn-icon">
                <i className="feather-arrow-right"></i>
              </span>
              <span className="btn-icon">
                <i className="feather-arrow-right"></i>
              </span>
            </span>
          </button>
        </div>
      </form> */}

      <iframe
        src="https://irepute.in/google-ad-repute/"
        width="100%"
        height="600"
        frameborder="0"
        allowfullscreen
      ></iframe>
    </div>
  );
};

export default OnlineSchoolForm;
